name: Deploy to VPS

on:
  push:
    branches:
      - main  # Adjust if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}       # Your VPS IP or hostname
        username: ${{ secrets.VPS_USER }}   # Your SSH username
        key: ${{ secrets.VPS_PRIVATE_KEY }} # Your private SSH key
        script: |
          cd /var/www/testnodeapp
          git pull origin main              # Replace 'main' if your branch is different
          npm install
          pm2 restart testnodeapp


name: Deploy

# Trigger the workflow on push and
# pull request events on the master branch
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: "cd /var/www/miniblog && ./.scripts/deploy.sh"